# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

project:
  type: website
website:
  title: "OceanBench"
  favicon: favicon.png
  open-graph: true
  navbar:
    logo: assets/favicon-light.png
    logo-alt: "OceanBench logo."
    left:
      - href: index.qmd
        text: Scores
      - challengers.qmd
      - about.qmd
  repo-url: https://github.com/mercator-ocean/oceanbench
  repo-actions: [edit, source, issue]
  repo-subdir: website
  page-footer: |
    Powered by:
    [![](https://datalab.dive.edito.eu/custom-resources/logos/Full_EU_DTO_Banner.jpeg){height=65px}](https://edito.eu)
format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
