# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

name: Run tests
on: [push]
jobs:
  tests:
    runs-on: self-hosted
    timeout-minutes: 150
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          micromamba-binary-path: ${{ runner.temp }}/bin/micromamba
          environment-file: conda_environment_test.yaml
          environment-name: oceanbench_test_${{ github.ref_name }}_${{ github.sha }}
          condarc-file: .condarc
          cache-environment: true
          post-cleanup: 'all'
      - name: Run tests
        env:
          COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
          COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TEST_ENVIRONMENT_NAME: oceanbench_test_${{ github.ref_name }}_${{ github.sha }}
        run: |
          pip install --editable .
          make evaluate-samples SAMPLE_FILES=assets/glonet_1_degree_sample.py
        shell: micromamba-shell {0}
      - name: Archive generated notebooks
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-notebooks
          path: |
            *_sample.report.ipynb
